### ISSUE TITLE
Separate file for validation function..

### ISSUE THREAD

**Issue by LRagji** [PredixDev/px-validation#1]
Should the validation function reside always in a new file? cant we refer to a function which is in the existing file where the component is used...? the problem i am facing is with polymer build it vulcanises everything into one html file to reduce network request but by design of px validation it requires the validation function to reside in another file for which a separate request has to be made.. multiply that with n components i have in our app.. is there any better way to handle this?

```
<px-validation>
  <px-validator validation-method="isNumber" import="px-example-validator.html"></px-validator>
  <px-validator multi-step-validation='["isNumber", "isRed", "isBlue"]' import="px-example-validator.html"></px-validator>
</px-validation>
```

**Comment by mdwragg** [comment]
Sounds like you're really close to this. Can you propose a pull request with the behaviour you are wanting? Thanks.
