### ISSUE TITLE
The validation-method property to be able to send arguments to the function used for validations

### ISSUE THREAD

**Issue by LuisKings** [PredixDev/px-validation#2]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

Enhancement:
Expected behavior: To be able to pass on arguments to the functions used in the validation-method property. An use case would be to validate a typed number to be between a particular range.

Actual behavior: The only argument passed on to the function used in the validation-method property is the actual value typed.

## Steps to reproduce the problem:

Running the px-validation component along with is px-validator does not allow to manually insert any arguments. No further steps

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Latest version of px-validation (1.1.3), Browser Chrome 63, macOS Sierra 10.12.6, used in MacBook Air 13" Early 2015

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
Hi Luis - I've added this functionality in v1.2.0 by using `.apply` so that all arguments passed to the `validate` function will be passed along to your validation method. I've added [an example validator](https://github.com/PredixDev/px-validation/blob/master/px-example-validator.html#L23-L29) to the demo that shows this functionality. Great suggestion, thanks.

**Comment by LuisKings** [comment]
Thanks! I guess this works if I'm calling programmatically the validate function. If I'm using the px-data-table-column component, which triggers the validate function automatically when the cell value is changed, the approach as such wouldn't work... right?

**Comment by randyaskin** [comment]
Hmm, yeah, not so much. How would you imagine the arguments would get passed? Via a property?

**Comment by LuisKings** [comment]
Yeah, that'd work just fine

**Comment by randyaskin** [comment]
Give it a try with v1.3.0 of px-validation, I've added an `arguments` property to px-validator, so you can also provide them as an array in HTML, e.g.

    <px-data-table-column name="first">
      <px-validation>
        <px-validator validation-method="isBetween" arguments="[1,5]">
        </px-validator>
      </px-validation>
    </px-data-table-column>

**Comment by LuisKings** [comment]
Thanks! That looks exactly what I need!
